
logging:
  config: classpath:logback.xml

server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: test
    password: Test@12345678
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB ???? ??

jwt:
  SECRET_KEY: kang
  ACCESS_TOKEN_VALIDATION_SECOND: 1000000
  #REFRESH_TOKEN_VALIDATION_SECOND: 1000*60*60*24*7
  ACCESS_TOKEN_NAME: accessToken
  REFRESH_TOKEN_NAME: refreshToken